MLM: true
alpha: 0.9
batch_size: 64
beta: 0.999
bias_lr_factor: 2.0
cmt_depth: 4
dataset_name: CUHK-PEDES
distributed: false
eval_period: 1
gamma: 0.1
id_loss_weight: 1.0
img_aug: true
img_size: !!python/tuple
- 384
- 128
local_rank: 0
log_period: 100
loss_names: sdm+id+mlm
lr: 1.0e-05
lr_factor: 5.0
lrscheduler: cosine
masked_token_rate: 0.8
masked_token_unchanged_rate: 0.1
milestones: !!python/tuple
- 20
- 50
mlm_loss_weight: 1.0
momentum: 0.9
name: irra_fx
num_epoch: 60
num_instance: 4
num_workers: 8
optimizer: Adam
output_dir: logs/CUHK-PEDES/irra_cuhk
power: 0.9
pretrain_choice: ViT-B/16
resume: false
resume_ckpt_file: ''
root_dir: ./data
sampler: random
stride_size: 16
target_lr: 0
temperature: 0.02
test_batch_size: 512
text_length: 77
training: true
val_dataset: test
vocab_size: 49408
warmup_epochs: 5
warmup_factor: 0.1
warmup_method: linear
weight_decay: 4.0e-05
weight_decay_bias: 0.0
